package RingPackage;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;

/**
 * a testing class for Polynomial methods
 * @author Vidyut Veedgav
 */
public class PolynomialTest {
    
    /**
     * testing the toString() method
     * AUTOGENERATED
     */
    @Test
    public void testToString() {
        Polynomial<Integer> poly = Polynomial.from(List.of(1, 2, 3, 4));
        assertEquals("Polynomial [coefficients=[1, 2, 3, 4]]", poly.toString());
    }
}
